#!/bin/bash
# Script for running the auto-configuration and activation of ANN

make

rm -f ./output/*.out
rm -f ./output/*.dat

EXP=$1
PRC=$2

for (( j=1; j<=$EXP; j++ ))
do
	echo 'Experiment ' $j
        mpirun -n $PRC ./annMPCA $j 100 false
done

./annMLP $EXP $PRC